x-service: &service
  env_file: ./.env
  restart: always 

services:
  backend:
    <<: *service
    container_name: backend-dev
    build: ./backend
    volumes:
      - ./backend:/usr/src/app

  frontend:
    <<: *service
    container_name: frontend-dev
    build: ./frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
  
  nginx:
    <<: *service
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - frontend