x-service: &service
  env_file: ./.env
  restart: always 

services:
  backend:
    <<: *service
    image: jeangmrch/musikea-backend:${IMAGES_VERSION:-latest}

  frontend:
    <<: *service
    image: jeangmrch/musikea-frontend:${IMAGES_VERSION:-latest}
    depends_on:
      - backend

  nginx:
    <<: *service
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - frontend
