name: Build and Publish Docker Image

on:
  pull_request:
    branches:
      - main # CI sur PR (tests)
  push:
    branches:
      - main # Merge Trunk : build + push image avec SHA
  release:
    types:
      - published # Release : build + push image avec nom de release
  workflow_dispatch: # Permet d'exécuter l'action manuellement

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

  build-and-push:
    name: Build & Push Docker Image
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'release'
    strategy:
      matrix:
        service: [frontend, backend]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set Docker Tag
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            TAG=${{ github.ref_name }}
          else
            TAG=${{ github.sha }}
          fi
          TAG=${TAG//\//-}   # Remplace les "/" par "-"
          TAG=${TAG// /}      # Supprime les espaces
          TAG=${TAG,,}        # Convertit en minuscules
          echo "DOCKER_TAG=$TAG" >> $GITHUB_ENV

      - name: Build and Push image
        uses: docker/build-push-action@v5
        env:
          DOCKER_TAG: ${{ env.DOCKER_TAG }}
        with:
          context: ${{ matrix.service }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}-${{ matrix.service }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}-${{ matrix.service }}:${{ env.DOCKER_TAG }}
